name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Docker image to Amazon ECR
      env:
        ECR_REPOSITORY: springbootapps
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.ecr-login.outputs.registry }}:$ECR_REPOSITORY:$IMAGE_TAG
        docker push ${{ steps.ecr-login.outputs.registry }}:$ECR_REPOSITORY:$IMAGE_TAG

    - name: Update ECS service with new task definition
      id: update-ecs-task
      uses: aws-actions/amazon-ecs-update-task-definition@v2
      with:
        task-definition: springboot-app-task-definition
        container-name: springboot-ecr
        image: ${{ steps.ecr-login.outputs.registry }}:${{ springbootapps }}:${{ github.sha }}
        family: springboot-app-task-definition

    - name: Deploy ECS service
      uses: aws-actions/amazon-ecs-deploy-service@v2
      with:
        cluster: ${{ secrets.ECS_CLUSTER }}
        service: ${{ secrets.ECS_SERVICE }}
        force-new-deployment: true
